### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by netgfx** [khawars/KSTokenView#54]
More specifically Swift 3.0 and Carthage support.

**Comment by alexkaessner** [comment]
@khawars **At least Swift 2.3 support would be awesome!** 👍 Otherwise Xcode 8 has a problem to build it.

The only errors Xcode shows are these. Should be easy to fix:
<img width="837" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6615076/18455010/ca4edfae-7947-11e6-8bbf-ba23acdb44ca.png">

**Comment by khawars** [comment]
@netgfx  and @alexkaessner I am back on the earth for a couple of days :) I'll try to fix as many issues as possible and will try to add support of Swift 3.0

**Comment by alexkaessner** [comment]
@khawars Nice and thanks! Maybe you should first do a small Swift 2.3 update before you move on to Swift 3. So we can still use the framework (with an older release) if we don't want to update to Swift 3 yet.

**Comment by mspasov** [comment]
@alexkaessner , @khawars I just did #57, should work under swift 2.2 and 2.3. Untested :)

**Comment by khawars** [comment]
Updated with Swift 2.3 and 3.0.
User ```master``` branch for Swift 3.0, and ```develop/swift2.3``` for 2.3. Please reopen for any related issue.
